/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as PagamentoBloqueadoRouteImport } from './routes/pagamento-bloqueado'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContaEmAnaliseRouteImport } from './routes/conta-em-analise'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoIndexRouteImport } from './routes/demo.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DemoVendasClientesRouteImport } from './routes/demo.vendas-clientes'
import { Route as DemoRoboDivulgadorRouteImport } from './routes/demo.robo-divulgador'
import { Route as DemoProdutosRouteImport } from './routes/demo.produtos'
import { Route as DemoPrecificacaoRouteImport } from './routes/demo.precificacao'
import { Route as DemoGruposRouteImport } from './routes/demo.grupos'
import { Route as DashboardVendasClientesRouteImport } from './routes/dashboard.vendas-clientes'
import { Route as DashboardValidarCadastrosRouteImport } from './routes/dashboard.validar-cadastros'
import { Route as DashboardTutoriaisRouteImport } from './routes/dashboard.tutoriais'
import { Route as DashboardRoboDivulgadorRouteImport } from './routes/dashboard.robo-divulgador'
import { Route as DashboardProdutosRouteImport } from './routes/dashboard.produtos'
import { Route as DashboardPrecificacaoRouteImport } from './routes/dashboard.precificacao'
import { Route as DashboardMeusProdutosRouteImport } from './routes/dashboard.meus-produtos'
import { Route as DashboardMetricasRouteImport } from './routes/dashboard.metricas'
import { Route as DashboardImpulsionarVendasRouteImport } from './routes/dashboard.impulsionar-vendas'
import { Route as DashboardGruposRouteImport } from './routes/dashboard.grupos'
import { Route as DashboardConfiguracoesRouteImport } from './routes/dashboard.configuracoes'
import { Route as DashboardConectarContasRouteImport } from './routes/dashboard.conectar-contas'
import { Route as DashboardAdicionarAdmsRouteImport } from './routes/dashboard.adicionar-adms'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoBloqueadoRoute = PagamentoBloqueadoRouteImport.update({
  id: '/pagamento-bloqueado',
  path: '/pagamento-bloqueado',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaEmAnaliseRoute = ContaEmAnaliseRouteImport.update({
  id: '/conta-em-analise',
  path: '/conta-em-analise',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DemoRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DemoVendasClientesRoute = DemoVendasClientesRouteImport.update({
  id: '/vendas-clientes',
  path: '/vendas-clientes',
  getParentRoute: () => DemoRoute,
} as any)
const DemoRoboDivulgadorRoute = DemoRoboDivulgadorRouteImport.update({
  id: '/robo-divulgador',
  path: '/robo-divulgador',
  getParentRoute: () => DemoRoute,
} as any)
const DemoProdutosRoute = DemoProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => DemoRoute,
} as any)
const DemoPrecificacaoRoute = DemoPrecificacaoRouteImport.update({
  id: '/precificacao',
  path: '/precificacao',
  getParentRoute: () => DemoRoute,
} as any)
const DemoGruposRoute = DemoGruposRouteImport.update({
  id: '/grupos',
  path: '/grupos',
  getParentRoute: () => DemoRoute,
} as any)
const DashboardVendasClientesRoute = DashboardVendasClientesRouteImport.update({
  id: '/vendas-clientes',
  path: '/vendas-clientes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardValidarCadastrosRoute =
  DashboardValidarCadastrosRouteImport.update({
    id: '/validar-cadastros',
    path: '/validar-cadastros',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardTutoriaisRoute = DashboardTutoriaisRouteImport.update({
  id: '/tutoriais',
  path: '/tutoriais',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRoboDivulgadorRoute = DashboardRoboDivulgadorRouteImport.update({
  id: '/robo-divulgador',
  path: '/robo-divulgador',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProdutosRoute = DashboardProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPrecificacaoRoute = DashboardPrecificacaoRouteImport.update({
  id: '/precificacao',
  path: '/precificacao',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMeusProdutosRoute = DashboardMeusProdutosRouteImport.update({
  id: '/meus-produtos',
  path: '/meus-produtos',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMetricasRoute = DashboardMetricasRouteImport.update({
  id: '/metricas',
  path: '/metricas',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardImpulsionarVendasRoute =
  DashboardImpulsionarVendasRouteImport.update({
    id: '/impulsionar-vendas',
    path: '/impulsionar-vendas',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardGruposRoute = DashboardGruposRouteImport.update({
  id: '/grupos',
  path: '/grupos',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConfiguracoesRoute = DashboardConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConectarContasRoute = DashboardConectarContasRouteImport.update({
  id: '/conectar-contas',
  path: '/conectar-contas',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdicionarAdmsRoute = DashboardAdicionarAdmsRouteImport.update({
  id: '/adicionar-adms',
  path: '/adicionar-adms',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conta-em-analise': typeof ContaEmAnaliseRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/demo': typeof DemoRouteWithChildren
  '/login': typeof LoginRoute
  '/pagamento-bloqueado': typeof PagamentoBloqueadoRoute
  '/planos': typeof PlanosRoute
  '/register': typeof RegisterRoute
  '/dashboard/adicionar-adms': typeof DashboardAdicionarAdmsRoute
  '/dashboard/conectar-contas': typeof DashboardConectarContasRoute
  '/dashboard/configuracoes': typeof DashboardConfiguracoesRoute
  '/dashboard/grupos': typeof DashboardGruposRoute
  '/dashboard/impulsionar-vendas': typeof DashboardImpulsionarVendasRoute
  '/dashboard/metricas': typeof DashboardMetricasRoute
  '/dashboard/meus-produtos': typeof DashboardMeusProdutosRoute
  '/dashboard/precificacao': typeof DashboardPrecificacaoRoute
  '/dashboard/produtos': typeof DashboardProdutosRoute
  '/dashboard/robo-divulgador': typeof DashboardRoboDivulgadorRoute
  '/dashboard/tutoriais': typeof DashboardTutoriaisRoute
  '/dashboard/validar-cadastros': typeof DashboardValidarCadastrosRoute
  '/dashboard/vendas-clientes': typeof DashboardVendasClientesRoute
  '/demo/grupos': typeof DemoGruposRoute
  '/demo/precificacao': typeof DemoPrecificacaoRoute
  '/demo/produtos': typeof DemoProdutosRoute
  '/demo/robo-divulgador': typeof DemoRoboDivulgadorRoute
  '/demo/vendas-clientes': typeof DemoVendasClientesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/demo/': typeof DemoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conta-em-analise': typeof ContaEmAnaliseRoute
  '/login': typeof LoginRoute
  '/pagamento-bloqueado': typeof PagamentoBloqueadoRoute
  '/planos': typeof PlanosRoute
  '/register': typeof RegisterRoute
  '/dashboard/adicionar-adms': typeof DashboardAdicionarAdmsRoute
  '/dashboard/conectar-contas': typeof DashboardConectarContasRoute
  '/dashboard/configuracoes': typeof DashboardConfiguracoesRoute
  '/dashboard/grupos': typeof DashboardGruposRoute
  '/dashboard/impulsionar-vendas': typeof DashboardImpulsionarVendasRoute
  '/dashboard/metricas': typeof DashboardMetricasRoute
  '/dashboard/meus-produtos': typeof DashboardMeusProdutosRoute
  '/dashboard/precificacao': typeof DashboardPrecificacaoRoute
  '/dashboard/produtos': typeof DashboardProdutosRoute
  '/dashboard/robo-divulgador': typeof DashboardRoboDivulgadorRoute
  '/dashboard/tutoriais': typeof DashboardTutoriaisRoute
  '/dashboard/validar-cadastros': typeof DashboardValidarCadastrosRoute
  '/dashboard/vendas-clientes': typeof DashboardVendasClientesRoute
  '/demo/grupos': typeof DemoGruposRoute
  '/demo/precificacao': typeof DemoPrecificacaoRoute
  '/demo/produtos': typeof DemoProdutosRoute
  '/demo/robo-divulgador': typeof DemoRoboDivulgadorRoute
  '/demo/vendas-clientes': typeof DemoVendasClientesRoute
  '/dashboard': typeof DashboardIndexRoute
  '/demo': typeof DemoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conta-em-analise': typeof ContaEmAnaliseRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/demo': typeof DemoRouteWithChildren
  '/login': typeof LoginRoute
  '/pagamento-bloqueado': typeof PagamentoBloqueadoRoute
  '/planos': typeof PlanosRoute
  '/register': typeof RegisterRoute
  '/dashboard/adicionar-adms': typeof DashboardAdicionarAdmsRoute
  '/dashboard/conectar-contas': typeof DashboardConectarContasRoute
  '/dashboard/configuracoes': typeof DashboardConfiguracoesRoute
  '/dashboard/grupos': typeof DashboardGruposRoute
  '/dashboard/impulsionar-vendas': typeof DashboardImpulsionarVendasRoute
  '/dashboard/metricas': typeof DashboardMetricasRoute
  '/dashboard/meus-produtos': typeof DashboardMeusProdutosRoute
  '/dashboard/precificacao': typeof DashboardPrecificacaoRoute
  '/dashboard/produtos': typeof DashboardProdutosRoute
  '/dashboard/robo-divulgador': typeof DashboardRoboDivulgadorRoute
  '/dashboard/tutoriais': typeof DashboardTutoriaisRoute
  '/dashboard/validar-cadastros': typeof DashboardValidarCadastrosRoute
  '/dashboard/vendas-clientes': typeof DashboardVendasClientesRoute
  '/demo/grupos': typeof DemoGruposRoute
  '/demo/precificacao': typeof DemoPrecificacaoRoute
  '/demo/produtos': typeof DemoProdutosRoute
  '/demo/robo-divulgador': typeof DemoRoboDivulgadorRoute
  '/demo/vendas-clientes': typeof DemoVendasClientesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/demo/': typeof DemoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conta-em-analise'
    | '/dashboard'
    | '/demo'
    | '/login'
    | '/pagamento-bloqueado'
    | '/planos'
    | '/register'
    | '/dashboard/adicionar-adms'
    | '/dashboard/conectar-contas'
    | '/dashboard/configuracoes'
    | '/dashboard/grupos'
    | '/dashboard/impulsionar-vendas'
    | '/dashboard/metricas'
    | '/dashboard/meus-produtos'
    | '/dashboard/precificacao'
    | '/dashboard/produtos'
    | '/dashboard/robo-divulgador'
    | '/dashboard/tutoriais'
    | '/dashboard/validar-cadastros'
    | '/dashboard/vendas-clientes'
    | '/demo/grupos'
    | '/demo/precificacao'
    | '/demo/produtos'
    | '/demo/robo-divulgador'
    | '/demo/vendas-clientes'
    | '/dashboard/'
    | '/demo/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conta-em-analise'
    | '/login'
    | '/pagamento-bloqueado'
    | '/planos'
    | '/register'
    | '/dashboard/adicionar-adms'
    | '/dashboard/conectar-contas'
    | '/dashboard/configuracoes'
    | '/dashboard/grupos'
    | '/dashboard/impulsionar-vendas'
    | '/dashboard/metricas'
    | '/dashboard/meus-produtos'
    | '/dashboard/precificacao'
    | '/dashboard/produtos'
    | '/dashboard/robo-divulgador'
    | '/dashboard/tutoriais'
    | '/dashboard/validar-cadastros'
    | '/dashboard/vendas-clientes'
    | '/demo/grupos'
    | '/demo/precificacao'
    | '/demo/produtos'
    | '/demo/robo-divulgador'
    | '/demo/vendas-clientes'
    | '/dashboard'
    | '/demo'
  id:
    | '__root__'
    | '/'
    | '/conta-em-analise'
    | '/dashboard'
    | '/demo'
    | '/login'
    | '/pagamento-bloqueado'
    | '/planos'
    | '/register'
    | '/dashboard/adicionar-adms'
    | '/dashboard/conectar-contas'
    | '/dashboard/configuracoes'
    | '/dashboard/grupos'
    | '/dashboard/impulsionar-vendas'
    | '/dashboard/metricas'
    | '/dashboard/meus-produtos'
    | '/dashboard/precificacao'
    | '/dashboard/produtos'
    | '/dashboard/robo-divulgador'
    | '/dashboard/tutoriais'
    | '/dashboard/validar-cadastros'
    | '/dashboard/vendas-clientes'
    | '/demo/grupos'
    | '/demo/precificacao'
    | '/demo/produtos'
    | '/demo/robo-divulgador'
    | '/demo/vendas-clientes'
    | '/dashboard/'
    | '/demo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContaEmAnaliseRoute: typeof ContaEmAnaliseRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DemoRoute: typeof DemoRouteWithChildren
  LoginRoute: typeof LoginRoute
  PagamentoBloqueadoRoute: typeof PagamentoBloqueadoRoute
  PlanosRoute: typeof PlanosRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento-bloqueado': {
      id: '/pagamento-bloqueado'
      path: '/pagamento-bloqueado'
      fullPath: '/pagamento-bloqueado'
      preLoaderRoute: typeof PagamentoBloqueadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta-em-analise': {
      id: '/conta-em-analise'
      path: '/conta-em-analise'
      fullPath: '/conta-em-analise'
      preLoaderRoute: typeof ContaEmAnaliseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/': {
      id: '/demo/'
      path: '/'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof DemoRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/demo/vendas-clientes': {
      id: '/demo/vendas-clientes'
      path: '/vendas-clientes'
      fullPath: '/demo/vendas-clientes'
      preLoaderRoute: typeof DemoVendasClientesRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/robo-divulgador': {
      id: '/demo/robo-divulgador'
      path: '/robo-divulgador'
      fullPath: '/demo/robo-divulgador'
      preLoaderRoute: typeof DemoRoboDivulgadorRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/produtos': {
      id: '/demo/produtos'
      path: '/produtos'
      fullPath: '/demo/produtos'
      preLoaderRoute: typeof DemoProdutosRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/precificacao': {
      id: '/demo/precificacao'
      path: '/precificacao'
      fullPath: '/demo/precificacao'
      preLoaderRoute: typeof DemoPrecificacaoRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/grupos': {
      id: '/demo/grupos'
      path: '/grupos'
      fullPath: '/demo/grupos'
      preLoaderRoute: typeof DemoGruposRouteImport
      parentRoute: typeof DemoRoute
    }
    '/dashboard/vendas-clientes': {
      id: '/dashboard/vendas-clientes'
      path: '/vendas-clientes'
      fullPath: '/dashboard/vendas-clientes'
      preLoaderRoute: typeof DashboardVendasClientesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/validar-cadastros': {
      id: '/dashboard/validar-cadastros'
      path: '/validar-cadastros'
      fullPath: '/dashboard/validar-cadastros'
      preLoaderRoute: typeof DashboardValidarCadastrosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tutoriais': {
      id: '/dashboard/tutoriais'
      path: '/tutoriais'
      fullPath: '/dashboard/tutoriais'
      preLoaderRoute: typeof DashboardTutoriaisRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/robo-divulgador': {
      id: '/dashboard/robo-divulgador'
      path: '/robo-divulgador'
      fullPath: '/dashboard/robo-divulgador'
      preLoaderRoute: typeof DashboardRoboDivulgadorRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/produtos': {
      id: '/dashboard/produtos'
      path: '/produtos'
      fullPath: '/dashboard/produtos'
      preLoaderRoute: typeof DashboardProdutosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/precificacao': {
      id: '/dashboard/precificacao'
      path: '/precificacao'
      fullPath: '/dashboard/precificacao'
      preLoaderRoute: typeof DashboardPrecificacaoRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/meus-produtos': {
      id: '/dashboard/meus-produtos'
      path: '/meus-produtos'
      fullPath: '/dashboard/meus-produtos'
      preLoaderRoute: typeof DashboardMeusProdutosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/metricas': {
      id: '/dashboard/metricas'
      path: '/metricas'
      fullPath: '/dashboard/metricas'
      preLoaderRoute: typeof DashboardMetricasRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/impulsionar-vendas': {
      id: '/dashboard/impulsionar-vendas'
      path: '/impulsionar-vendas'
      fullPath: '/dashboard/impulsionar-vendas'
      preLoaderRoute: typeof DashboardImpulsionarVendasRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/grupos': {
      id: '/dashboard/grupos'
      path: '/grupos'
      fullPath: '/dashboard/grupos'
      preLoaderRoute: typeof DashboardGruposRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/configuracoes': {
      id: '/dashboard/configuracoes'
      path: '/configuracoes'
      fullPath: '/dashboard/configuracoes'
      preLoaderRoute: typeof DashboardConfiguracoesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/conectar-contas': {
      id: '/dashboard/conectar-contas'
      path: '/conectar-contas'
      fullPath: '/dashboard/conectar-contas'
      preLoaderRoute: typeof DashboardConectarContasRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/adicionar-adms': {
      id: '/dashboard/adicionar-adms'
      path: '/adicionar-adms'
      fullPath: '/dashboard/adicionar-adms'
      preLoaderRoute: typeof DashboardAdicionarAdmsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAdicionarAdmsRoute: typeof DashboardAdicionarAdmsRoute
  DashboardConectarContasRoute: typeof DashboardConectarContasRoute
  DashboardConfiguracoesRoute: typeof DashboardConfiguracoesRoute
  DashboardGruposRoute: typeof DashboardGruposRoute
  DashboardImpulsionarVendasRoute: typeof DashboardImpulsionarVendasRoute
  DashboardMetricasRoute: typeof DashboardMetricasRoute
  DashboardMeusProdutosRoute: typeof DashboardMeusProdutosRoute
  DashboardPrecificacaoRoute: typeof DashboardPrecificacaoRoute
  DashboardProdutosRoute: typeof DashboardProdutosRoute
  DashboardRoboDivulgadorRoute: typeof DashboardRoboDivulgadorRoute
  DashboardTutoriaisRoute: typeof DashboardTutoriaisRoute
  DashboardValidarCadastrosRoute: typeof DashboardValidarCadastrosRoute
  DashboardVendasClientesRoute: typeof DashboardVendasClientesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdicionarAdmsRoute: DashboardAdicionarAdmsRoute,
  DashboardConectarContasRoute: DashboardConectarContasRoute,
  DashboardConfiguracoesRoute: DashboardConfiguracoesRoute,
  DashboardGruposRoute: DashboardGruposRoute,
  DashboardImpulsionarVendasRoute: DashboardImpulsionarVendasRoute,
  DashboardMetricasRoute: DashboardMetricasRoute,
  DashboardMeusProdutosRoute: DashboardMeusProdutosRoute,
  DashboardPrecificacaoRoute: DashboardPrecificacaoRoute,
  DashboardProdutosRoute: DashboardProdutosRoute,
  DashboardRoboDivulgadorRoute: DashboardRoboDivulgadorRoute,
  DashboardTutoriaisRoute: DashboardTutoriaisRoute,
  DashboardValidarCadastrosRoute: DashboardValidarCadastrosRoute,
  DashboardVendasClientesRoute: DashboardVendasClientesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface DemoRouteChildren {
  DemoGruposRoute: typeof DemoGruposRoute
  DemoPrecificacaoRoute: typeof DemoPrecificacaoRoute
  DemoProdutosRoute: typeof DemoProdutosRoute
  DemoRoboDivulgadorRoute: typeof DemoRoboDivulgadorRoute
  DemoVendasClientesRoute: typeof DemoVendasClientesRoute
  DemoIndexRoute: typeof DemoIndexRoute
}

const DemoRouteChildren: DemoRouteChildren = {
  DemoGruposRoute: DemoGruposRoute,
  DemoPrecificacaoRoute: DemoPrecificacaoRoute,
  DemoProdutosRoute: DemoProdutosRoute,
  DemoRoboDivulgadorRoute: DemoRoboDivulgadorRoute,
  DemoVendasClientesRoute: DemoVendasClientesRoute,
  DemoIndexRoute: DemoIndexRoute,
}

const DemoRouteWithChildren = DemoRoute._addFileChildren(DemoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContaEmAnaliseRoute: ContaEmAnaliseRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DemoRoute: DemoRouteWithChildren,
  LoginRoute: LoginRoute,
  PagamentoBloqueadoRoute: PagamentoBloqueadoRoute,
  PlanosRoute: PlanosRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
