/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendasRouteImport } from './routes/vendas'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as PlanosupRouteImport } from './routes/planosup'
import { Route as Planos3RouteImport } from './routes/planos3'
import { Route as Planos2RouteImport } from './routes/planos2'
import { Route as PagamentoBloqueadoRouteImport } from './routes/pagamento-bloqueado'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContaEmAnaliseRouteImport } from './routes/conta-em-analise'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoIndexRouteImport } from './routes/demo.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DemoVendasClientesRouteImport } from './routes/demo.vendas-clientes'
import { Route as DemoRoboDivulgadorRouteImport } from './routes/demo.robo-divulgador'
import { Route as DemoProdutosRouteImport } from './routes/demo.produtos'
import { Route as DemoPrecificacaoRouteImport } from './routes/demo.precificacao'
import { Route as DemoGruposRouteImport } from './routes/demo.grupos'
import { Route as DashboardVideoIaRouteImport } from './routes/dashboard.video-ia'
import { Route as DashboardValidarCadastrosRouteImport } from './routes/dashboard.validar-cadastros'
import { Route as DashboardRoboDivulgadorRouteImport } from './routes/dashboard.robo-divulgador'
import { Route as DashboardProdutosRouteImport } from './routes/dashboard.produtos'
import { Route as DashboardMetricasRouteImport } from './routes/dashboard.metricas'
import { Route as DashboardImpulsionarVendasRouteImport } from './routes/dashboard.impulsionar-vendas'
import { Route as DashboardGruposRouteImport } from './routes/dashboard.grupos'
import { Route as DashboardConfiguracoesRouteImport } from './routes/dashboard.configuracoes'
import { Route as DashboardConectarContasRouteImport } from './routes/dashboard.conectar-contas'
import { Route as DashboardImpulsionarVendasBackupRouteImport } from './routes/dashboard.impulsionar-vendas.backup'

const VendasRoute = VendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosupRoute = PlanosupRouteImport.update({
  id: '/planosup',
  path: '/planosup',
  getParentRoute: () => rootRouteImport,
} as any)
const Planos3Route = Planos3RouteImport.update({
  id: '/planos3',
  path: '/planos3',
  getParentRoute: () => rootRouteImport,
} as any)
const Planos2Route = Planos2RouteImport.update({
  id: '/planos2',
  path: '/planos2',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoBloqueadoRoute = PagamentoBloqueadoRouteImport.update({
  id: '/pagamento-bloqueado',
  path: '/pagamento-bloqueado',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaEmAnaliseRoute = ContaEmAnaliseRouteImport.update({
  id: '/conta-em-analise',
  path: '/conta-em-analise',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DemoRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DemoVendasClientesRoute = DemoVendasClientesRouteImport.update({
  id: '/vendas-clientes',
  path: '/vendas-clientes',
  getParentRoute: () => DemoRoute,
} as any)
const DemoRoboDivulgadorRoute = DemoRoboDivulgadorRouteImport.update({
  id: '/robo-divulgador',
  path: '/robo-divulgador',
  getParentRoute: () => DemoRoute,
} as any)
const DemoProdutosRoute = DemoProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => DemoRoute,
} as any)
const DemoPrecificacaoRoute = DemoPrecificacaoRouteImport.update({
  id: '/precificacao',
  path: '/precificacao',
  getParentRoute: () => DemoRoute,
} as any)
const DemoGruposRoute = DemoGruposRouteImport.update({
  id: '/grupos',
  path: '/grupos',
  getParentRoute: () => DemoRoute,
} as any)
const DashboardVideoIaRoute = DashboardVideoIaRouteImport.update({
  id: '/video-ia',
  path: '/video-ia',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardValidarCadastrosRoute =
  DashboardValidarCadastrosRouteImport.update({
    id: '/validar-cadastros',
    path: '/validar-cadastros',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardRoboDivulgadorRoute = DashboardRoboDivulgadorRouteImport.update({
  id: '/robo-divulgador',
  path: '/robo-divulgador',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProdutosRoute = DashboardProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMetricasRoute = DashboardMetricasRouteImport.update({
  id: '/metricas',
  path: '/metricas',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardImpulsionarVendasRoute =
  DashboardImpulsionarVendasRouteImport.update({
    id: '/impulsionar-vendas',
    path: '/impulsionar-vendas',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardGruposRoute = DashboardGruposRouteImport.update({
  id: '/grupos',
  path: '/grupos',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConfiguracoesRoute = DashboardConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConectarContasRoute = DashboardConectarContasRouteImport.update({
  id: '/conectar-contas',
  path: '/conectar-contas',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardImpulsionarVendasBackupRoute =
  DashboardImpulsionarVendasBackupRouteImport.update({
    id: '/backup',
    path: '/backup',
    getParentRoute: () => DashboardImpulsionarVendasRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conta-em-analise': typeof ContaEmAnaliseRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/demo': typeof DemoRouteWithChildren
  '/login': typeof LoginRoute
  '/pagamento-bloqueado': typeof PagamentoBloqueadoRoute
  '/planos2': typeof Planos2Route
  '/planos3': typeof Planos3Route
  '/planosup': typeof PlanosupRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/register': typeof RegisterRoute
  '/vendas': typeof VendasRoute
  '/dashboard/conectar-contas': typeof DashboardConectarContasRoute
  '/dashboard/configuracoes': typeof DashboardConfiguracoesRoute
  '/dashboard/grupos': typeof DashboardGruposRoute
  '/dashboard/impulsionar-vendas': typeof DashboardImpulsionarVendasRouteWithChildren
  '/dashboard/metricas': typeof DashboardMetricasRoute
  '/dashboard/produtos': typeof DashboardProdutosRoute
  '/dashboard/robo-divulgador': typeof DashboardRoboDivulgadorRoute
  '/dashboard/validar-cadastros': typeof DashboardValidarCadastrosRoute
  '/dashboard/video-ia': typeof DashboardVideoIaRoute
  '/demo/grupos': typeof DemoGruposRoute
  '/demo/precificacao': typeof DemoPrecificacaoRoute
  '/demo/produtos': typeof DemoProdutosRoute
  '/demo/robo-divulgador': typeof DemoRoboDivulgadorRoute
  '/demo/vendas-clientes': typeof DemoVendasClientesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/demo/': typeof DemoIndexRoute
  '/dashboard/impulsionar-vendas/backup': typeof DashboardImpulsionarVendasBackupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conta-em-analise': typeof ContaEmAnaliseRoute
  '/login': typeof LoginRoute
  '/pagamento-bloqueado': typeof PagamentoBloqueadoRoute
  '/planos2': typeof Planos2Route
  '/planos3': typeof Planos3Route
  '/planosup': typeof PlanosupRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/register': typeof RegisterRoute
  '/vendas': typeof VendasRoute
  '/dashboard/conectar-contas': typeof DashboardConectarContasRoute
  '/dashboard/configuracoes': typeof DashboardConfiguracoesRoute
  '/dashboard/grupos': typeof DashboardGruposRoute
  '/dashboard/impulsionar-vendas': typeof DashboardImpulsionarVendasRouteWithChildren
  '/dashboard/metricas': typeof DashboardMetricasRoute
  '/dashboard/produtos': typeof DashboardProdutosRoute
  '/dashboard/robo-divulgador': typeof DashboardRoboDivulgadorRoute
  '/dashboard/validar-cadastros': typeof DashboardValidarCadastrosRoute
  '/dashboard/video-ia': typeof DashboardVideoIaRoute
  '/demo/grupos': typeof DemoGruposRoute
  '/demo/precificacao': typeof DemoPrecificacaoRoute
  '/demo/produtos': typeof DemoProdutosRoute
  '/demo/robo-divulgador': typeof DemoRoboDivulgadorRoute
  '/demo/vendas-clientes': typeof DemoVendasClientesRoute
  '/dashboard': typeof DashboardIndexRoute
  '/demo': typeof DemoIndexRoute
  '/dashboard/impulsionar-vendas/backup': typeof DashboardImpulsionarVendasBackupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conta-em-analise': typeof ContaEmAnaliseRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/demo': typeof DemoRouteWithChildren
  '/login': typeof LoginRoute
  '/pagamento-bloqueado': typeof PagamentoBloqueadoRoute
  '/planos2': typeof Planos2Route
  '/planos3': typeof Planos3Route
  '/planosup': typeof PlanosupRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/register': typeof RegisterRoute
  '/vendas': typeof VendasRoute
  '/dashboard/conectar-contas': typeof DashboardConectarContasRoute
  '/dashboard/configuracoes': typeof DashboardConfiguracoesRoute
  '/dashboard/grupos': typeof DashboardGruposRoute
  '/dashboard/impulsionar-vendas': typeof DashboardImpulsionarVendasRouteWithChildren
  '/dashboard/metricas': typeof DashboardMetricasRoute
  '/dashboard/produtos': typeof DashboardProdutosRoute
  '/dashboard/robo-divulgador': typeof DashboardRoboDivulgadorRoute
  '/dashboard/validar-cadastros': typeof DashboardValidarCadastrosRoute
  '/dashboard/video-ia': typeof DashboardVideoIaRoute
  '/demo/grupos': typeof DemoGruposRoute
  '/demo/precificacao': typeof DemoPrecificacaoRoute
  '/demo/produtos': typeof DemoProdutosRoute
  '/demo/robo-divulgador': typeof DemoRoboDivulgadorRoute
  '/demo/vendas-clientes': typeof DemoVendasClientesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/demo/': typeof DemoIndexRoute
  '/dashboard/impulsionar-vendas/backup': typeof DashboardImpulsionarVendasBackupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conta-em-analise'
    | '/dashboard'
    | '/demo'
    | '/login'
    | '/pagamento-bloqueado'
    | '/planos2'
    | '/planos3'
    | '/planosup'
    | '/redefinir-senha'
    | '/register'
    | '/vendas'
    | '/dashboard/conectar-contas'
    | '/dashboard/configuracoes'
    | '/dashboard/grupos'
    | '/dashboard/impulsionar-vendas'
    | '/dashboard/metricas'
    | '/dashboard/produtos'
    | '/dashboard/robo-divulgador'
    | '/dashboard/validar-cadastros'
    | '/dashboard/video-ia'
    | '/demo/grupos'
    | '/demo/precificacao'
    | '/demo/produtos'
    | '/demo/robo-divulgador'
    | '/demo/vendas-clientes'
    | '/dashboard/'
    | '/demo/'
    | '/dashboard/impulsionar-vendas/backup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conta-em-analise'
    | '/login'
    | '/pagamento-bloqueado'
    | '/planos2'
    | '/planos3'
    | '/planosup'
    | '/redefinir-senha'
    | '/register'
    | '/vendas'
    | '/dashboard/conectar-contas'
    | '/dashboard/configuracoes'
    | '/dashboard/grupos'
    | '/dashboard/impulsionar-vendas'
    | '/dashboard/metricas'
    | '/dashboard/produtos'
    | '/dashboard/robo-divulgador'
    | '/dashboard/validar-cadastros'
    | '/dashboard/video-ia'
    | '/demo/grupos'
    | '/demo/precificacao'
    | '/demo/produtos'
    | '/demo/robo-divulgador'
    | '/demo/vendas-clientes'
    | '/dashboard'
    | '/demo'
    | '/dashboard/impulsionar-vendas/backup'
  id:
    | '__root__'
    | '/'
    | '/conta-em-analise'
    | '/dashboard'
    | '/demo'
    | '/login'
    | '/pagamento-bloqueado'
    | '/planos2'
    | '/planos3'
    | '/planosup'
    | '/redefinir-senha'
    | '/register'
    | '/vendas'
    | '/dashboard/conectar-contas'
    | '/dashboard/configuracoes'
    | '/dashboard/grupos'
    | '/dashboard/impulsionar-vendas'
    | '/dashboard/metricas'
    | '/dashboard/produtos'
    | '/dashboard/robo-divulgador'
    | '/dashboard/validar-cadastros'
    | '/dashboard/video-ia'
    | '/demo/grupos'
    | '/demo/precificacao'
    | '/demo/produtos'
    | '/demo/robo-divulgador'
    | '/demo/vendas-clientes'
    | '/dashboard/'
    | '/demo/'
    | '/dashboard/impulsionar-vendas/backup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContaEmAnaliseRoute: typeof ContaEmAnaliseRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DemoRoute: typeof DemoRouteWithChildren
  LoginRoute: typeof LoginRoute
  PagamentoBloqueadoRoute: typeof PagamentoBloqueadoRoute
  Planos2Route: typeof Planos2Route
  Planos3Route: typeof Planos3Route
  PlanosupRoute: typeof PlanosupRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  RegisterRoute: typeof RegisterRoute
  VendasRoute: typeof VendasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendas': {
      id: '/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof VendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planosup': {
      id: '/planosup'
      path: '/planosup'
      fullPath: '/planosup'
      preLoaderRoute: typeof PlanosupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos3': {
      id: '/planos3'
      path: '/planos3'
      fullPath: '/planos3'
      preLoaderRoute: typeof Planos3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos2': {
      id: '/planos2'
      path: '/planos2'
      fullPath: '/planos2'
      preLoaderRoute: typeof Planos2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento-bloqueado': {
      id: '/pagamento-bloqueado'
      path: '/pagamento-bloqueado'
      fullPath: '/pagamento-bloqueado'
      preLoaderRoute: typeof PagamentoBloqueadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta-em-analise': {
      id: '/conta-em-analise'
      path: '/conta-em-analise'
      fullPath: '/conta-em-analise'
      preLoaderRoute: typeof ContaEmAnaliseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/': {
      id: '/demo/'
      path: '/'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof DemoRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/demo/vendas-clientes': {
      id: '/demo/vendas-clientes'
      path: '/vendas-clientes'
      fullPath: '/demo/vendas-clientes'
      preLoaderRoute: typeof DemoVendasClientesRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/robo-divulgador': {
      id: '/demo/robo-divulgador'
      path: '/robo-divulgador'
      fullPath: '/demo/robo-divulgador'
      preLoaderRoute: typeof DemoRoboDivulgadorRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/produtos': {
      id: '/demo/produtos'
      path: '/produtos'
      fullPath: '/demo/produtos'
      preLoaderRoute: typeof DemoProdutosRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/precificacao': {
      id: '/demo/precificacao'
      path: '/precificacao'
      fullPath: '/demo/precificacao'
      preLoaderRoute: typeof DemoPrecificacaoRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/grupos': {
      id: '/demo/grupos'
      path: '/grupos'
      fullPath: '/demo/grupos'
      preLoaderRoute: typeof DemoGruposRouteImport
      parentRoute: typeof DemoRoute
    }
    '/dashboard/video-ia': {
      id: '/dashboard/video-ia'
      path: '/video-ia'
      fullPath: '/dashboard/video-ia'
      preLoaderRoute: typeof DashboardVideoIaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/validar-cadastros': {
      id: '/dashboard/validar-cadastros'
      path: '/validar-cadastros'
      fullPath: '/dashboard/validar-cadastros'
      preLoaderRoute: typeof DashboardValidarCadastrosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/robo-divulgador': {
      id: '/dashboard/robo-divulgador'
      path: '/robo-divulgador'
      fullPath: '/dashboard/robo-divulgador'
      preLoaderRoute: typeof DashboardRoboDivulgadorRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/produtos': {
      id: '/dashboard/produtos'
      path: '/produtos'
      fullPath: '/dashboard/produtos'
      preLoaderRoute: typeof DashboardProdutosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/metricas': {
      id: '/dashboard/metricas'
      path: '/metricas'
      fullPath: '/dashboard/metricas'
      preLoaderRoute: typeof DashboardMetricasRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/impulsionar-vendas': {
      id: '/dashboard/impulsionar-vendas'
      path: '/impulsionar-vendas'
      fullPath: '/dashboard/impulsionar-vendas'
      preLoaderRoute: typeof DashboardImpulsionarVendasRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/grupos': {
      id: '/dashboard/grupos'
      path: '/grupos'
      fullPath: '/dashboard/grupos'
      preLoaderRoute: typeof DashboardGruposRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/configuracoes': {
      id: '/dashboard/configuracoes'
      path: '/configuracoes'
      fullPath: '/dashboard/configuracoes'
      preLoaderRoute: typeof DashboardConfiguracoesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/conectar-contas': {
      id: '/dashboard/conectar-contas'
      path: '/conectar-contas'
      fullPath: '/dashboard/conectar-contas'
      preLoaderRoute: typeof DashboardConectarContasRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/impulsionar-vendas/backup': {
      id: '/dashboard/impulsionar-vendas/backup'
      path: '/backup'
      fullPath: '/dashboard/impulsionar-vendas/backup'
      preLoaderRoute: typeof DashboardImpulsionarVendasBackupRouteImport
      parentRoute: typeof DashboardImpulsionarVendasRoute
    }
  }
}

interface DashboardImpulsionarVendasRouteChildren {
  DashboardImpulsionarVendasBackupRoute: typeof DashboardImpulsionarVendasBackupRoute
}

const DashboardImpulsionarVendasRouteChildren: DashboardImpulsionarVendasRouteChildren =
  {
    DashboardImpulsionarVendasBackupRoute:
      DashboardImpulsionarVendasBackupRoute,
  }

const DashboardImpulsionarVendasRouteWithChildren =
  DashboardImpulsionarVendasRoute._addFileChildren(
    DashboardImpulsionarVendasRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardConectarContasRoute: typeof DashboardConectarContasRoute
  DashboardConfiguracoesRoute: typeof DashboardConfiguracoesRoute
  DashboardGruposRoute: typeof DashboardGruposRoute
  DashboardImpulsionarVendasRoute: typeof DashboardImpulsionarVendasRouteWithChildren
  DashboardMetricasRoute: typeof DashboardMetricasRoute
  DashboardProdutosRoute: typeof DashboardProdutosRoute
  DashboardRoboDivulgadorRoute: typeof DashboardRoboDivulgadorRoute
  DashboardValidarCadastrosRoute: typeof DashboardValidarCadastrosRoute
  DashboardVideoIaRoute: typeof DashboardVideoIaRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardConectarContasRoute: DashboardConectarContasRoute,
  DashboardConfiguracoesRoute: DashboardConfiguracoesRoute,
  DashboardGruposRoute: DashboardGruposRoute,
  DashboardImpulsionarVendasRoute: DashboardImpulsionarVendasRouteWithChildren,
  DashboardMetricasRoute: DashboardMetricasRoute,
  DashboardProdutosRoute: DashboardProdutosRoute,
  DashboardRoboDivulgadorRoute: DashboardRoboDivulgadorRoute,
  DashboardValidarCadastrosRoute: DashboardValidarCadastrosRoute,
  DashboardVideoIaRoute: DashboardVideoIaRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface DemoRouteChildren {
  DemoGruposRoute: typeof DemoGruposRoute
  DemoPrecificacaoRoute: typeof DemoPrecificacaoRoute
  DemoProdutosRoute: typeof DemoProdutosRoute
  DemoRoboDivulgadorRoute: typeof DemoRoboDivulgadorRoute
  DemoVendasClientesRoute: typeof DemoVendasClientesRoute
  DemoIndexRoute: typeof DemoIndexRoute
}

const DemoRouteChildren: DemoRouteChildren = {
  DemoGruposRoute: DemoGruposRoute,
  DemoPrecificacaoRoute: DemoPrecificacaoRoute,
  DemoProdutosRoute: DemoProdutosRoute,
  DemoRoboDivulgadorRoute: DemoRoboDivulgadorRoute,
  DemoVendasClientesRoute: DemoVendasClientesRoute,
  DemoIndexRoute: DemoIndexRoute,
}

const DemoRouteWithChildren = DemoRoute._addFileChildren(DemoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContaEmAnaliseRoute: ContaEmAnaliseRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DemoRoute: DemoRouteWithChildren,
  LoginRoute: LoginRoute,
  PagamentoBloqueadoRoute: PagamentoBloqueadoRoute,
  Planos2Route: Planos2Route,
  Planos3Route: Planos3Route,
  PlanosupRoute: PlanosupRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  RegisterRoute: RegisterRoute,
  VendasRoute: VendasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
