/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as PagamentoBloqueadoRouteImport } from './routes/pagamento-bloqueado'
import { Route as Ofertas9RouteImport } from './routes/ofertas9'
import { Route as Ofertas8RouteImport } from './routes/ofertas8'
import { Route as Ofertas7RouteImport } from './routes/ofertas7'
import { Route as Ofertas6RouteImport } from './routes/ofertas6'
import { Route as Ofertas5RouteImport } from './routes/ofertas5'
import { Route as MercadolivrecombrRouteImport } from './routes/mercadolivrecombr'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContaEmAnaliseRouteImport } from './routes/conta-em-analise'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoIndexRouteImport } from './routes/demo.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DemoVendasClientesRouteImport } from './routes/demo.vendas-clientes'
import { Route as DemoRoboDivulgadorRouteImport } from './routes/demo.robo-divulgador'
import { Route as DemoProdutosRouteImport } from './routes/demo.produtos'
import { Route as DemoPrecificacaoRouteImport } from './routes/demo.precificacao'
import { Route as DemoGruposRouteImport } from './routes/demo.grupos'
import { Route as DashboardVideoIaRouteImport } from './routes/dashboard.video-ia'
import { Route as DashboardValidarCadastrosRouteImport } from './routes/dashboard.validar-cadastros'
import { Route as DashboardSuporteAdminRouteImport } from './routes/dashboard.suporte-admin'
import { Route as DashboardSuporteRouteImport } from './routes/dashboard.suporte'
import { Route as DashboardRoboDivulgadorRouteImport } from './routes/dashboard.robo-divulgador'
import { Route as DashboardProdutosRouteImport } from './routes/dashboard.produtos'
import { Route as DashboardMetricasRouteImport } from './routes/dashboard.metricas'
import { Route as DashboardImpulsionarVendasRouteImport } from './routes/dashboard.impulsionar-vendas'
import { Route as DashboardGruposRouteImport } from './routes/dashboard.grupos'
import { Route as DashboardConfiguracoesRouteImport } from './routes/dashboard.configuracoes'
import { Route as DashboardConectarContasRouteImport } from './routes/dashboard.conectar-contas'
import { Route as DashboardAulasRouteImport } from './routes/dashboard.aulas'
import { Route as DashboardImpulsionarVendasBackupRouteImport } from './routes/dashboard.impulsionar-vendas.backup'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoBloqueadoRoute = PagamentoBloqueadoRouteImport.update({
  id: '/pagamento-bloqueado',
  path: '/pagamento-bloqueado',
  getParentRoute: () => rootRouteImport,
} as any)
const Ofertas9Route = Ofertas9RouteImport.update({
  id: '/ofertas9',
  path: '/ofertas9',
  getParentRoute: () => rootRouteImport,
} as any)
const Ofertas8Route = Ofertas8RouteImport.update({
  id: '/ofertas8',
  path: '/ofertas8',
  getParentRoute: () => rootRouteImport,
} as any)
const Ofertas7Route = Ofertas7RouteImport.update({
  id: '/ofertas7',
  path: '/ofertas7',
  getParentRoute: () => rootRouteImport,
} as any)
const Ofertas6Route = Ofertas6RouteImport.update({
  id: '/ofertas6',
  path: '/ofertas6',
  getParentRoute: () => rootRouteImport,
} as any)
const Ofertas5Route = Ofertas5RouteImport.update({
  id: '/ofertas5',
  path: '/ofertas5',
  getParentRoute: () => rootRouteImport,
} as any)
const MercadolivrecombrRoute = MercadolivrecombrRouteImport.update({
  id: '/mercadolivrecombr',
  path: '/mercadolivrecombr',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaEmAnaliseRoute = ContaEmAnaliseRouteImport.update({
  id: '/conta-em-analise',
  path: '/conta-em-analise',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DemoRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DemoVendasClientesRoute = DemoVendasClientesRouteImport.update({
  id: '/vendas-clientes',
  path: '/vendas-clientes',
  getParentRoute: () => DemoRoute,
} as any)
const DemoRoboDivulgadorRoute = DemoRoboDivulgadorRouteImport.update({
  id: '/robo-divulgador',
  path: '/robo-divulgador',
  getParentRoute: () => DemoRoute,
} as any)
const DemoProdutosRoute = DemoProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => DemoRoute,
} as any)
const DemoPrecificacaoRoute = DemoPrecificacaoRouteImport.update({
  id: '/precificacao',
  path: '/precificacao',
  getParentRoute: () => DemoRoute,
} as any)
const DemoGruposRoute = DemoGruposRouteImport.update({
  id: '/grupos',
  path: '/grupos',
  getParentRoute: () => DemoRoute,
} as any)
const DashboardVideoIaRoute = DashboardVideoIaRouteImport.update({
  id: '/video-ia',
  path: '/video-ia',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardValidarCadastrosRoute =
  DashboardValidarCadastrosRouteImport.update({
    id: '/validar-cadastros',
    path: '/validar-cadastros',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSuporteAdminRoute = DashboardSuporteAdminRouteImport.update({
  id: '/suporte-admin',
  path: '/suporte-admin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSuporteRoute = DashboardSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRoboDivulgadorRoute = DashboardRoboDivulgadorRouteImport.update({
  id: '/robo-divulgador',
  path: '/robo-divulgador',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProdutosRoute = DashboardProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMetricasRoute = DashboardMetricasRouteImport.update({
  id: '/metricas',
  path: '/metricas',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardImpulsionarVendasRoute =
  DashboardImpulsionarVendasRouteImport.update({
    id: '/impulsionar-vendas',
    path: '/impulsionar-vendas',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardGruposRoute = DashboardGruposRouteImport.update({
  id: '/grupos',
  path: '/grupos',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConfiguracoesRoute = DashboardConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConectarContasRoute = DashboardConectarContasRouteImport.update({
  id: '/conectar-contas',
  path: '/conectar-contas',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAulasRoute = DashboardAulasRouteImport.update({
  id: '/aulas',
  path: '/aulas',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardImpulsionarVendasBackupRoute =
  DashboardImpulsionarVendasBackupRouteImport.update({
    id: '/backup',
    path: '/backup',
    getParentRoute: () => DashboardImpulsionarVendasRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conta-em-analise': typeof ContaEmAnaliseRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/demo': typeof DemoRouteWithChildren
  '/login': typeof LoginRoute
  '/mercadolivrecombr': typeof MercadolivrecombrRoute
  '/ofertas5': typeof Ofertas5Route
  '/ofertas6': typeof Ofertas6Route
  '/ofertas7': typeof Ofertas7Route
  '/ofertas8': typeof Ofertas8Route
  '/ofertas9': typeof Ofertas9Route
  '/pagamento-bloqueado': typeof PagamentoBloqueadoRoute
  '/painel': typeof PainelRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/register': typeof RegisterRoute
  '/dashboard/aulas': typeof DashboardAulasRoute
  '/dashboard/conectar-contas': typeof DashboardConectarContasRoute
  '/dashboard/configuracoes': typeof DashboardConfiguracoesRoute
  '/dashboard/grupos': typeof DashboardGruposRoute
  '/dashboard/impulsionar-vendas': typeof DashboardImpulsionarVendasRouteWithChildren
  '/dashboard/metricas': typeof DashboardMetricasRoute
  '/dashboard/produtos': typeof DashboardProdutosRoute
  '/dashboard/robo-divulgador': typeof DashboardRoboDivulgadorRoute
  '/dashboard/suporte': typeof DashboardSuporteRoute
  '/dashboard/suporte-admin': typeof DashboardSuporteAdminRoute
  '/dashboard/validar-cadastros': typeof DashboardValidarCadastrosRoute
  '/dashboard/video-ia': typeof DashboardVideoIaRoute
  '/demo/grupos': typeof DemoGruposRoute
  '/demo/precificacao': typeof DemoPrecificacaoRoute
  '/demo/produtos': typeof DemoProdutosRoute
  '/demo/robo-divulgador': typeof DemoRoboDivulgadorRoute
  '/demo/vendas-clientes': typeof DemoVendasClientesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/demo/': typeof DemoIndexRoute
  '/dashboard/impulsionar-vendas/backup': typeof DashboardImpulsionarVendasBackupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conta-em-analise': typeof ContaEmAnaliseRoute
  '/login': typeof LoginRoute
  '/mercadolivrecombr': typeof MercadolivrecombrRoute
  '/ofertas5': typeof Ofertas5Route
  '/ofertas6': typeof Ofertas6Route
  '/ofertas7': typeof Ofertas7Route
  '/ofertas8': typeof Ofertas8Route
  '/ofertas9': typeof Ofertas9Route
  '/pagamento-bloqueado': typeof PagamentoBloqueadoRoute
  '/painel': typeof PainelRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/register': typeof RegisterRoute
  '/dashboard/aulas': typeof DashboardAulasRoute
  '/dashboard/conectar-contas': typeof DashboardConectarContasRoute
  '/dashboard/configuracoes': typeof DashboardConfiguracoesRoute
  '/dashboard/grupos': typeof DashboardGruposRoute
  '/dashboard/impulsionar-vendas': typeof DashboardImpulsionarVendasRouteWithChildren
  '/dashboard/metricas': typeof DashboardMetricasRoute
  '/dashboard/produtos': typeof DashboardProdutosRoute
  '/dashboard/robo-divulgador': typeof DashboardRoboDivulgadorRoute
  '/dashboard/suporte': typeof DashboardSuporteRoute
  '/dashboard/suporte-admin': typeof DashboardSuporteAdminRoute
  '/dashboard/validar-cadastros': typeof DashboardValidarCadastrosRoute
  '/dashboard/video-ia': typeof DashboardVideoIaRoute
  '/demo/grupos': typeof DemoGruposRoute
  '/demo/precificacao': typeof DemoPrecificacaoRoute
  '/demo/produtos': typeof DemoProdutosRoute
  '/demo/robo-divulgador': typeof DemoRoboDivulgadorRoute
  '/demo/vendas-clientes': typeof DemoVendasClientesRoute
  '/dashboard': typeof DashboardIndexRoute
  '/demo': typeof DemoIndexRoute
  '/dashboard/impulsionar-vendas/backup': typeof DashboardImpulsionarVendasBackupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conta-em-analise': typeof ContaEmAnaliseRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/demo': typeof DemoRouteWithChildren
  '/login': typeof LoginRoute
  '/mercadolivrecombr': typeof MercadolivrecombrRoute
  '/ofertas5': typeof Ofertas5Route
  '/ofertas6': typeof Ofertas6Route
  '/ofertas7': typeof Ofertas7Route
  '/ofertas8': typeof Ofertas8Route
  '/ofertas9': typeof Ofertas9Route
  '/pagamento-bloqueado': typeof PagamentoBloqueadoRoute
  '/painel': typeof PainelRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/register': typeof RegisterRoute
  '/dashboard/aulas': typeof DashboardAulasRoute
  '/dashboard/conectar-contas': typeof DashboardConectarContasRoute
  '/dashboard/configuracoes': typeof DashboardConfiguracoesRoute
  '/dashboard/grupos': typeof DashboardGruposRoute
  '/dashboard/impulsionar-vendas': typeof DashboardImpulsionarVendasRouteWithChildren
  '/dashboard/metricas': typeof DashboardMetricasRoute
  '/dashboard/produtos': typeof DashboardProdutosRoute
  '/dashboard/robo-divulgador': typeof DashboardRoboDivulgadorRoute
  '/dashboard/suporte': typeof DashboardSuporteRoute
  '/dashboard/suporte-admin': typeof DashboardSuporteAdminRoute
  '/dashboard/validar-cadastros': typeof DashboardValidarCadastrosRoute
  '/dashboard/video-ia': typeof DashboardVideoIaRoute
  '/demo/grupos': typeof DemoGruposRoute
  '/demo/precificacao': typeof DemoPrecificacaoRoute
  '/demo/produtos': typeof DemoProdutosRoute
  '/demo/robo-divulgador': typeof DemoRoboDivulgadorRoute
  '/demo/vendas-clientes': typeof DemoVendasClientesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/demo/': typeof DemoIndexRoute
  '/dashboard/impulsionar-vendas/backup': typeof DashboardImpulsionarVendasBackupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conta-em-analise'
    | '/dashboard'
    | '/demo'
    | '/login'
    | '/mercadolivrecombr'
    | '/ofertas5'
    | '/ofertas6'
    | '/ofertas7'
    | '/ofertas8'
    | '/ofertas9'
    | '/pagamento-bloqueado'
    | '/painel'
    | '/redefinir-senha'
    | '/register'
    | '/dashboard/aulas'
    | '/dashboard/conectar-contas'
    | '/dashboard/configuracoes'
    | '/dashboard/grupos'
    | '/dashboard/impulsionar-vendas'
    | '/dashboard/metricas'
    | '/dashboard/produtos'
    | '/dashboard/robo-divulgador'
    | '/dashboard/suporte'
    | '/dashboard/suporte-admin'
    | '/dashboard/validar-cadastros'
    | '/dashboard/video-ia'
    | '/demo/grupos'
    | '/demo/precificacao'
    | '/demo/produtos'
    | '/demo/robo-divulgador'
    | '/demo/vendas-clientes'
    | '/dashboard/'
    | '/demo/'
    | '/dashboard/impulsionar-vendas/backup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conta-em-analise'
    | '/login'
    | '/mercadolivrecombr'
    | '/ofertas5'
    | '/ofertas6'
    | '/ofertas7'
    | '/ofertas8'
    | '/ofertas9'
    | '/pagamento-bloqueado'
    | '/painel'
    | '/redefinir-senha'
    | '/register'
    | '/dashboard/aulas'
    | '/dashboard/conectar-contas'
    | '/dashboard/configuracoes'
    | '/dashboard/grupos'
    | '/dashboard/impulsionar-vendas'
    | '/dashboard/metricas'
    | '/dashboard/produtos'
    | '/dashboard/robo-divulgador'
    | '/dashboard/suporte'
    | '/dashboard/suporte-admin'
    | '/dashboard/validar-cadastros'
    | '/dashboard/video-ia'
    | '/demo/grupos'
    | '/demo/precificacao'
    | '/demo/produtos'
    | '/demo/robo-divulgador'
    | '/demo/vendas-clientes'
    | '/dashboard'
    | '/demo'
    | '/dashboard/impulsionar-vendas/backup'
  id:
    | '__root__'
    | '/'
    | '/conta-em-analise'
    | '/dashboard'
    | '/demo'
    | '/login'
    | '/mercadolivrecombr'
    | '/ofertas5'
    | '/ofertas6'
    | '/ofertas7'
    | '/ofertas8'
    | '/ofertas9'
    | '/pagamento-bloqueado'
    | '/painel'
    | '/redefinir-senha'
    | '/register'
    | '/dashboard/aulas'
    | '/dashboard/conectar-contas'
    | '/dashboard/configuracoes'
    | '/dashboard/grupos'
    | '/dashboard/impulsionar-vendas'
    | '/dashboard/metricas'
    | '/dashboard/produtos'
    | '/dashboard/robo-divulgador'
    | '/dashboard/suporte'
    | '/dashboard/suporte-admin'
    | '/dashboard/validar-cadastros'
    | '/dashboard/video-ia'
    | '/demo/grupos'
    | '/demo/precificacao'
    | '/demo/produtos'
    | '/demo/robo-divulgador'
    | '/demo/vendas-clientes'
    | '/dashboard/'
    | '/demo/'
    | '/dashboard/impulsionar-vendas/backup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContaEmAnaliseRoute: typeof ContaEmAnaliseRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DemoRoute: typeof DemoRouteWithChildren
  LoginRoute: typeof LoginRoute
  MercadolivrecombrRoute: typeof MercadolivrecombrRoute
  Ofertas5Route: typeof Ofertas5Route
  Ofertas6Route: typeof Ofertas6Route
  Ofertas7Route: typeof Ofertas7Route
  Ofertas8Route: typeof Ofertas8Route
  Ofertas9Route: typeof Ofertas9Route
  PagamentoBloqueadoRoute: typeof PagamentoBloqueadoRoute
  PainelRoute: typeof PainelRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento-bloqueado': {
      id: '/pagamento-bloqueado'
      path: '/pagamento-bloqueado'
      fullPath: '/pagamento-bloqueado'
      preLoaderRoute: typeof PagamentoBloqueadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ofertas9': {
      id: '/ofertas9'
      path: '/ofertas9'
      fullPath: '/ofertas9'
      preLoaderRoute: typeof Ofertas9RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ofertas8': {
      id: '/ofertas8'
      path: '/ofertas8'
      fullPath: '/ofertas8'
      preLoaderRoute: typeof Ofertas8RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ofertas7': {
      id: '/ofertas7'
      path: '/ofertas7'
      fullPath: '/ofertas7'
      preLoaderRoute: typeof Ofertas7RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ofertas6': {
      id: '/ofertas6'
      path: '/ofertas6'
      fullPath: '/ofertas6'
      preLoaderRoute: typeof Ofertas6RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ofertas5': {
      id: '/ofertas5'
      path: '/ofertas5'
      fullPath: '/ofertas5'
      preLoaderRoute: typeof Ofertas5RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mercadolivrecombr': {
      id: '/mercadolivrecombr'
      path: '/mercadolivrecombr'
      fullPath: '/mercadolivrecombr'
      preLoaderRoute: typeof MercadolivrecombrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta-em-analise': {
      id: '/conta-em-analise'
      path: '/conta-em-analise'
      fullPath: '/conta-em-analise'
      preLoaderRoute: typeof ContaEmAnaliseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/': {
      id: '/demo/'
      path: '/'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof DemoRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/demo/vendas-clientes': {
      id: '/demo/vendas-clientes'
      path: '/vendas-clientes'
      fullPath: '/demo/vendas-clientes'
      preLoaderRoute: typeof DemoVendasClientesRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/robo-divulgador': {
      id: '/demo/robo-divulgador'
      path: '/robo-divulgador'
      fullPath: '/demo/robo-divulgador'
      preLoaderRoute: typeof DemoRoboDivulgadorRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/produtos': {
      id: '/demo/produtos'
      path: '/produtos'
      fullPath: '/demo/produtos'
      preLoaderRoute: typeof DemoProdutosRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/precificacao': {
      id: '/demo/precificacao'
      path: '/precificacao'
      fullPath: '/demo/precificacao'
      preLoaderRoute: typeof DemoPrecificacaoRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/grupos': {
      id: '/demo/grupos'
      path: '/grupos'
      fullPath: '/demo/grupos'
      preLoaderRoute: typeof DemoGruposRouteImport
      parentRoute: typeof DemoRoute
    }
    '/dashboard/video-ia': {
      id: '/dashboard/video-ia'
      path: '/video-ia'
      fullPath: '/dashboard/video-ia'
      preLoaderRoute: typeof DashboardVideoIaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/validar-cadastros': {
      id: '/dashboard/validar-cadastros'
      path: '/validar-cadastros'
      fullPath: '/dashboard/validar-cadastros'
      preLoaderRoute: typeof DashboardValidarCadastrosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/suporte-admin': {
      id: '/dashboard/suporte-admin'
      path: '/suporte-admin'
      fullPath: '/dashboard/suporte-admin'
      preLoaderRoute: typeof DashboardSuporteAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/suporte': {
      id: '/dashboard/suporte'
      path: '/suporte'
      fullPath: '/dashboard/suporte'
      preLoaderRoute: typeof DashboardSuporteRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/robo-divulgador': {
      id: '/dashboard/robo-divulgador'
      path: '/robo-divulgador'
      fullPath: '/dashboard/robo-divulgador'
      preLoaderRoute: typeof DashboardRoboDivulgadorRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/produtos': {
      id: '/dashboard/produtos'
      path: '/produtos'
      fullPath: '/dashboard/produtos'
      preLoaderRoute: typeof DashboardProdutosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/metricas': {
      id: '/dashboard/metricas'
      path: '/metricas'
      fullPath: '/dashboard/metricas'
      preLoaderRoute: typeof DashboardMetricasRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/impulsionar-vendas': {
      id: '/dashboard/impulsionar-vendas'
      path: '/impulsionar-vendas'
      fullPath: '/dashboard/impulsionar-vendas'
      preLoaderRoute: typeof DashboardImpulsionarVendasRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/grupos': {
      id: '/dashboard/grupos'
      path: '/grupos'
      fullPath: '/dashboard/grupos'
      preLoaderRoute: typeof DashboardGruposRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/configuracoes': {
      id: '/dashboard/configuracoes'
      path: '/configuracoes'
      fullPath: '/dashboard/configuracoes'
      preLoaderRoute: typeof DashboardConfiguracoesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/conectar-contas': {
      id: '/dashboard/conectar-contas'
      path: '/conectar-contas'
      fullPath: '/dashboard/conectar-contas'
      preLoaderRoute: typeof DashboardConectarContasRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/aulas': {
      id: '/dashboard/aulas'
      path: '/aulas'
      fullPath: '/dashboard/aulas'
      preLoaderRoute: typeof DashboardAulasRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/impulsionar-vendas/backup': {
      id: '/dashboard/impulsionar-vendas/backup'
      path: '/backup'
      fullPath: '/dashboard/impulsionar-vendas/backup'
      preLoaderRoute: typeof DashboardImpulsionarVendasBackupRouteImport
      parentRoute: typeof DashboardImpulsionarVendasRoute
    }
  }
}

interface DashboardImpulsionarVendasRouteChildren {
  DashboardImpulsionarVendasBackupRoute: typeof DashboardImpulsionarVendasBackupRoute
}

const DashboardImpulsionarVendasRouteChildren: DashboardImpulsionarVendasRouteChildren =
  {
    DashboardImpulsionarVendasBackupRoute:
      DashboardImpulsionarVendasBackupRoute,
  }

const DashboardImpulsionarVendasRouteWithChildren =
  DashboardImpulsionarVendasRoute._addFileChildren(
    DashboardImpulsionarVendasRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardAulasRoute: typeof DashboardAulasRoute
  DashboardConectarContasRoute: typeof DashboardConectarContasRoute
  DashboardConfiguracoesRoute: typeof DashboardConfiguracoesRoute
  DashboardGruposRoute: typeof DashboardGruposRoute
  DashboardImpulsionarVendasRoute: typeof DashboardImpulsionarVendasRouteWithChildren
  DashboardMetricasRoute: typeof DashboardMetricasRoute
  DashboardProdutosRoute: typeof DashboardProdutosRoute
  DashboardRoboDivulgadorRoute: typeof DashboardRoboDivulgadorRoute
  DashboardSuporteRoute: typeof DashboardSuporteRoute
  DashboardSuporteAdminRoute: typeof DashboardSuporteAdminRoute
  DashboardValidarCadastrosRoute: typeof DashboardValidarCadastrosRoute
  DashboardVideoIaRoute: typeof DashboardVideoIaRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAulasRoute: DashboardAulasRoute,
  DashboardConectarContasRoute: DashboardConectarContasRoute,
  DashboardConfiguracoesRoute: DashboardConfiguracoesRoute,
  DashboardGruposRoute: DashboardGruposRoute,
  DashboardImpulsionarVendasRoute: DashboardImpulsionarVendasRouteWithChildren,
  DashboardMetricasRoute: DashboardMetricasRoute,
  DashboardProdutosRoute: DashboardProdutosRoute,
  DashboardRoboDivulgadorRoute: DashboardRoboDivulgadorRoute,
  DashboardSuporteRoute: DashboardSuporteRoute,
  DashboardSuporteAdminRoute: DashboardSuporteAdminRoute,
  DashboardValidarCadastrosRoute: DashboardValidarCadastrosRoute,
  DashboardVideoIaRoute: DashboardVideoIaRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface DemoRouteChildren {
  DemoGruposRoute: typeof DemoGruposRoute
  DemoPrecificacaoRoute: typeof DemoPrecificacaoRoute
  DemoProdutosRoute: typeof DemoProdutosRoute
  DemoRoboDivulgadorRoute: typeof DemoRoboDivulgadorRoute
  DemoVendasClientesRoute: typeof DemoVendasClientesRoute
  DemoIndexRoute: typeof DemoIndexRoute
}

const DemoRouteChildren: DemoRouteChildren = {
  DemoGruposRoute: DemoGruposRoute,
  DemoPrecificacaoRoute: DemoPrecificacaoRoute,
  DemoProdutosRoute: DemoProdutosRoute,
  DemoRoboDivulgadorRoute: DemoRoboDivulgadorRoute,
  DemoVendasClientesRoute: DemoVendasClientesRoute,
  DemoIndexRoute: DemoIndexRoute,
}

const DemoRouteWithChildren = DemoRoute._addFileChildren(DemoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContaEmAnaliseRoute: ContaEmAnaliseRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DemoRoute: DemoRouteWithChildren,
  LoginRoute: LoginRoute,
  MercadolivrecombrRoute: MercadolivrecombrRoute,
  Ofertas5Route: Ofertas5Route,
  Ofertas6Route: Ofertas6Route,
  Ofertas7Route: Ofertas7Route,
  Ofertas8Route: Ofertas8Route,
  Ofertas9Route: Ofertas9Route,
  PagamentoBloqueadoRoute: PagamentoBloqueadoRoute,
  PainelRoute: PainelRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
